// import './instance'
// import './lifeCycle'
// import './data-binding'
// import './computed'
// import './directive'
// import './define'
// import './extend'
// import './v-model'
// import './feature'
import './render'
